### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by kianmeng**
Found via:
- `codespell -S patches,bundled -L crate,struc,inout,statics,ist,ser,doas`
- `typos --format brief`.

### CODE REVIEW

**Comment by jwpjrdev** [comment]
my boy andy just got called out on his spelling 💀

**Review by Andy-Python-Programmer — APPROVED** [review]
LGTM. Thanks for the corrections :)

**Comment by Andy-Python-Programmer** [comment]
Thanks @kianmeng!

**Comment by kianmeng** [comment]
:partying_face: :partying_face: :partying_face: :partying_face: :partying_face:

**Pull request merged**
