### PR TITLE
replace aero.py with rusty build system

### PR DESCRIPTION
**Pull request by jwpjrdev**
this implementation will hopefully be faster and more maintainable

important things:
- [ ] building aero
- [ ] running qemu
- [ ] updating ci commands
- [ ] updating env commands (gitpod & codespaces)
- [ ] optimisation
- [ ] rust documentation
- [ ] implementing latest features in `aero_build` from aero.py

note to self: don't forget to add a comment referencing [this gist](https://gist.github.com/fnky/458719343aabd01cfb17a3a4f7296797) to the logging functions.

### CODE REVIEW

**Comment by jwpjrdev** [comment]
that's the goal! aiming to use the smallest, fastest crates i can find

**Comment by jwpjrdev** [comment]
won't be working on this until the 1st, ran out of hours on Gitpod 😢
i've written a good portion of it, just can't do anything with it yet

**Comment by jwpjrdev** [comment]
by the way, currently, just using `gumdrop` and `termcolor`. if colour isn't needed, i'll ditch `termcolor`.

**Comment by czapek1337** [comment]
gumdrop seems fine, you can get rid of termcolor as it seems to bring in a lot of winapi bullshit which is basically useless because aero doesn't have first class support for windows and it's a hefty crate (>1 MB), just implement ansi colors yourself with ansi escapes, it's very easy :')

**Comment by czapek1337** [comment]
additionally the newer windows terminal support ansi escapes just fine so it shouldn't be a problem, i'm not sure if termcolor gates the winapi dependency behind a feature, but if it does then it might be wise to disable it

**Comment by jwpjrdev** [comment]
cool, i'll look into that

**Comment by jwpjrdev** [comment]
looks like it only uses it when the compile target is windows but it's still pretty hefty.
https://github.com/BurntSushi/termcolor/blob/677f98b26a1b52f72303e1c9dfdc9ef68def8014/Cargo.toml#L21-L22

**Comment by jwpjrdev** [comment]
accidentally started the workspace from master instead of rust-build and had to force push like a fool 🥲

**Comment by amada95** [comment]
Just a comment, I think it's reasonable to say leaving out Windows/cygwin/etc compatibility for now should probably be fine, since anything WinApi is a massive pain and tends to add a lot of cruft/bloat. I'm going to take a look at what you have, and maybe throw some tests your way :)

**Comment by czapek1337** [comment]
> Just a comment, I think it's reasonable to say leaving out Windows/cygwin/etc compatibility for now should probably be fine, since anything WinApi is a massive pain and tends to add a lot of cruft/bloat. I'm going to take a look at what you have, and maybe throw some tests your way :)

I totally agree with that comment, the days of MSYS/Cygwin are numbered ever since WSL became a thing (and Windows 7 is EOL.) I don't think crippling our build system just to support exotic setups is a reasonable choice. Let's just keep it simple :^)

**Comment by jwpjrdev** [comment]
i need to pull some upstream changes but i cba yet

**Comment by MolassesLover** [comment]
There's a lot of serious issues when it comes to the build pipeline. For one, dependencies in [`tools/deps.sh`](https://github.com/Andy-Python-Programmer/aero/blob/41b4edc8342d915cb75d673fffb24b657de3ab7a/tools/deps.sh) seem to be dependent on package manager

**Comment by Andy-Python-Programmer** [comment]
This has now been resolved as `aero.py` is replaced with `make`.

**Pull request closed without merging**
