### PR TITLE
README: make it look look less sus

### PR DESCRIPTION
**Pull request by YusufKhan-improves-shit**
Some people may be sussed out by the amount of links to rick astley's wikipedia page and think its a rick roll. I removed a couple links so no one gets confused.

### CODE REVIEW

**Comment by pitust** [comment]
no the rickrolls are funny

**Comment by YusufKhan-gamedev** [comment]
> no the rickrolls are funny

If you think rickrolls are funny then create a pull request adding rick rolls smh, look at YusufKhan-improves-shit:master and look at how much better the readme is. Click on rick astley and see the wonderful wikipedia page on rick astley.

**Comment by czapek1337** [comment]
> If you think rickrolls are funny then create a pull request adding rick rolls smh

imho we've got the perfect amount of rick rolls right now, but I do kinda thing that the rick astley theme is a bit boring and unnecessary, but that's up to andy :^)

**Comment by YusufKhan-gamedev** [comment]
> mho we've got the perfect amount of rick rolls right now, but I do kinda think that the rick astley theme is a bit boring and unnecessary, but that's up to andy :^)

the amount of rickrolls we have rn is 0, look at my page and click on the wonderful rick astley, mwah!

**Comment by Andy-Python-Programmer** [comment]
rick rolls are fun but now its time to change the default background. I am not sure to what, but I think about farms or mountains will be a nice background :^)

**Comment by YusufKhan-gamedev** [comment]
> Rick rolls are fun but now its time to change the default background. I am not sure to what, but I think about farms or mountains will be a nice background :^)

Farms/hills are boring, its as boring as the windows wallpapers. Anyway, youve all seen the new page right?

**Comment by YusufKhan-improves-shit** [comment]
Derp! accidentally deleted the branch with changes! Ill include it in the "ports: add bootstrap.yml to begin the ports manager(less of a manager…" pr!  https://github.com/Andy-Python-Programmer/aero/pull/48

**Pull request closed without merging**
