### PR TITLE
Fix xbstrap bug in aero.py, add opendoas support

### PR DESCRIPTION
**Pull request by amada95**

### CODE REVIEW

**Comment by amada95** [comment]
Note: fixes for `tools/mkimage.sh` WIP, don't merge this yet!

**Comment by amada95** [comment]
`loop` Linux kernel module was not checked before use, causing issues on my system (and some others) which had no other reason to insert the module before `tools/mkimage.sh` is used.

**Review by Andy-Python-Programmer — APPROVED** [review]

**Comment by Andy-Python-Programmer** [comment]
Good catch, thanks @amada95!

**Comment by amada95** [comment]
Happy to help :)

**Pull request merged**
